### PR TITLE
Extract properties and methods from class' traits

### PR DESCRIPTION
**Pull request by scisssssssors**
Use case: Spiral framework has PrototypeTrait which simplifies access to frequently used services https://github.com/spiral/prototype/blob/master/src/Traits/PrototypeTrait.php. Available services are described in docblock of the trait itself to help gather completion suggestions.

Example:
```
<?php

/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 */

declare(strict_types=1);

namespace Spiral\Prototype\Traits;

use Spiral\Core\ContainerScope;
use Spiral\Core\Exception\ScopeException;
use Spiral\Prototype\Exception\PrototypeException;
use Spiral\Prototype\PrototypeRegistry;

/**
 * This DocComment is auto-generated, do not edit or commit this file to repository.
 * 
 * @property \App\App $app
 * @property \Spiral\Tokenizer\ClassesInterface $classLocator
 * @property \Spiral\Console\Console $console
 * @property \Psr\Container\ContainerInterface $container
 * @property \Spiral\Database\DatabaseInterface $db
 * @property \Spiral\Database\DatabaseProviderInterface $dbal
 * @property \Spiral\Encrypter\EncrypterInterface $encrypter
 * @property \Spiral\Boot\EnvironmentInterface $env
 * @property \Spiral\Files\FilesInterface $files
 * @property \Spiral\Security\GuardInterface $guard
 * @property \Spiral\Http\Http $http
 * @property \Spiral\Translator\TranslatorInterface $i18n
 * @property \Spiral\Http\Request\InputManager $input
 * @property \Spiral\Session\SessionScope $session
 * @property \Spiral\Cookies\CookieManager $cookies
 * @property \Psr\Log\LoggerInterface $logger
 * @property \Spiral\Logger\LogsInterface $logs
 * @property \Spiral\Boot\MemoryInterface $memory
 * @property \Cycle\ORM\ORMInterface $orm
 * @property \Spiral\Pagination\PaginationProviderInterface $paginators
 * @property \Spiral\Jobs\QueueInterface $queue
 * @property \Spiral\Http\Request\InputManager $request
 * @property \Spiral\Http\ResponseWrapper $response
 * @property \Spiral\Router\RouterInterface $router
 * @property \Spiral\Goridge\RPC $server
 * @property \Spiral\Snapshots\SnapshotterInterface $snapshots
 * @property \Spiral\Validation\ValidationInterface $validator
 * @property \Spiral\Views\ViewsInterface $views
 * @property \Spiral\Auth\AuthScope $auth
 * @property \Spiral\Auth\TokenStorageInterface $authTokens
 */
trait PrototypeTrait
{
```

Phpactor wouldn't recognize them, so here is PR to fix it.

### CODE REVIEW

**Comment by dantleech** [comment]
Brilliant thanks :+1: 

Do you think you could add a test case to [ReflectionTraitTest](https://github.com/phpactor/worse-reflection/blob/master/tests/Integration/Bridge/TolerantParser/Reflection/ReflectionTraitTest.php) similar to [the virtual property tests in ReflectionClassTest](https://github.com/phpactor/worse-reflection/blob/360a923947ac2c4646e81ebd12fa2d2391c94830/tests/Integration/Bridge) ?/TolerantParser/Reflection/ReflectionClassTest.php#L766-L773)

**Comment by dantleech** [comment]
Also please check PHPStan:

```
$ vendor/bin/phpstan analyse lib -c phpstan.neon

   0/161 [░░░░░░░░░░░░░░░░░░░░░░░░░░░░]   0%

  40/161 [▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░░░░░]  24%

  60/161 [▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░░░░]  37%

  80/161 [▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░░░░░]  49%

 100/161 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░░░░░░░░]  62%

 140/161 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓░░░░]  86%

 161/161 [▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓] 100%

 ------ -------------------------------------------------- 

  Line   Core/Virtual/VirtualReflectionClassDecorator.php  

 ------ -------------------------------------------------- 

  122    Variable $memberProvider might not be defined.    

  148    Variable $memberProvider might not be defined.    

 ------ -------------------------------------------------- 
```

you can run all the CI checks with `$ composer integrate`  I think.

**Comment by scisssssssors** [comment]
Thanks, I'll take a couple of days

**Comment by scisssssssors** [comment]
I think `ReflectionClassTest` isn't really a good place for this test because it's `VirtualReflectionClassDecorator` that has changed, not trait. Correct me if I'm wrong.

Also: is it worth adding `VirtualReflectionTraitDecorator` similar to `VirtualReflectionInterfaceDecorator`? I'm asking because I've just noticed this:
```
        foreach ($this->interfaces() as $interface) {
            assert($interface instanceof VirtualReflectionInterfaceDecorator);
            $virtualMethods = $virtualMethods->merge(
                $interface->virtualMethods()->byVisibilities([ Visibility::public(), Visibility::protected() ])
            );
        }
```
Now loop for traits looks like this:
```
        foreach ($this->memberProviders as $memberProvider) {
            $virtualProperties = $virtualProperties->merge(
                $memberProvider->provideMembers($this->serviceLocator, $this->class)->properties()
            );

            foreach ($this->traits() as $trait) {
                $virtualProperties = $virtualProperties->merge(
                    $memberProvider->provideMembers($this->serviceLocator, $trait)->properties()
                );
            }
        }
```
What do you think?

**Comment by dantleech** [comment]
> Thanks, I'll take a couple of days to figure everything out

Thanks

> I think ReflectionClassTest isn't really a good place for this test because

Assume you mean `ReflectionTraitTest`? Yes - in this case `ReflectionClassTest` would be the one.

> Also: is it worth adding VirtualReflectionTraitDecorator

Without trying I'm not sure: in the best case if we decorate the traits then the virtual members will automatically work with the reflection classes (and in which case `ReflectionTraitTest` would be the place)

**Comment by scisssssssors** [comment]
> Assume you mean ReflectionTraitTest? Yes - in this case ReflectionClassTest would be the one.
Yes, I had `ReflectionTraitTest` in mind, thanks for correction

Did a forced push to PR. Please confirm tests are sufficient. Not sure if "parent class" test is needed

**Comment by dantleech** [comment]
Thanks! Testing the parent class is good :+1:

**Pull request merged**
