### PR TITLE
Function reflection

### PR DESCRIPTION
**Pull request by dantleech**
TODO:

- [x] Name resolution for inferred types (prob. need some refactoring).
- [x] Parameter reflection
- [x] Function location
- [x] Symbol resolution

### CODE REVIEW

**Comment by haringsrob** [comment]
Not sure if this is all there was wrong but it fixes both phpstan and tests

```

**Comment by haringsrob** [comment]
If you can provide me some pointers or failing tests I can do some more.

**Comment by dantleech** [comment]
Thanks, it seems I thought the inferred (e.g. `@param Foobar`) type resolution would need some refactoring, so that could be quite tricky (it would affect all the existing similar code).

Reflecting parameters should be quite straight-forward, I guess.

Function location is basically creating a some strategy for locating functions in a source tree (probably by parsing all the composer file includes and registering any functions found there in a cached index if required - it might just be fast-enough in real-time.

Feel free to have a crack at any of that if you like, there is a Symfony Devs slack channel `#phpactor` if you want to chat about it.

`

**Comment by dantleech** [comment]
Function parameters are now implemented

**Pull request merged**
